version: 0.2

env:
  git-credential-helper: yes

phases:
  pre_build:
    commands:
#      - env && cat /codebuild/readonly/build-info.json && jq '.source' /codebuild/readonly/build-info.json
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Logging in to Amazon ECR ($AWS_DEFAULT_REGION)= ${REPOSITORY_URI}..."
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "${REPOSITORY_URI}"
      - echo '.git' >> .dockerignore
      - codebuild-breakpoint
  build:
    commands:
      - echo Build started on `date`
      - codebuild-breakpoint
      - echo Building the Docker image...
      - docker build -t "${REPOSITORY_URI}":latest -t "${REPOSITORY_URI}":"$${CODEBUILD_BUILD_NUMBER:-latest}" -t "${REPOSITORY_URI}":"$${COMMIT_HASH:-latest}" .
  post_build:
    commands:
      - echo Build completed on `date`
      - codebuild-breakpoint
      - echo Pushing the Docker image...
      - docker push --all-tags "${REPOSITORY_URI}"
      - printf '[{"name":"hello-world","imageUri":"%s"}]' ${REPOSITORY_URI}:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files:
      - imagedefinitions.json
      - flatspec.yaml
      - flattask.json
#  files:
#    - '**/*'
#  name: $IMAGE_NAME-$IMAGE_TAG
