version: 0.2

env:
  git-credential-helper: yes

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR ($AWS_DEFAULT_REGION)...
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
			- IMAGE_TAG=$CODEBUILD_SOURCE_VERSION
			- echo '.git' >> .dockerignore
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - docker build -t $REPOSITORY_URI/$IMAGE_REPO_NAME:latest -t $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push --all-tags $REPOSITORY_URI/$IMAGE_REPO_NAME

